services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: trucking-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: trucking-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - trucking-network

  # Backend API
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: trucking-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/trucking-app
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=3001
    depends_on:
      - mongodb
    networks:
      - trucking-network
    volumes:
      - ./api:/app
      - /app/node_modules

  # Frontend React
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: trucking-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - trucking-network
    environment:
      - VITE_API_URL=http://localhost:3001

volumes:
  mongodb_data:

networks:
  trucking-network:
    driver: bridge
